name: Test Suite
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@7aa0f7a606f182bd03a7adb28e0d710216101ca5 # main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint, Unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: 
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
    - name: Check out code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Setup Python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
    - name: Lint
      run: tox -vve lint
    - name: Unit Tests
      run: tox -vve unit
    - name: Upload Coverage
      uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192 # v1
      with:
        files: ./report/unit/coverage-xml
        flags: unittests # optional
